### ISSUE TITLE
Decay Time Constant

### ISSUE THREAD

**Issue by mbezaire** [BlueBrain/eFEL#114]
I am also not sure how to get the decay time constant to compute. For example, here I was trying to use it to calculate the sag time constant, but it is returning nan when I run it. (This is the same file that returns the negative of the input resistance, in case the one I attached to the reply on the other issue didn't make it to you.)

[MWE3.txt](https://github.com/BlueBrain/eFEL/files/1252793/MWE3.txt)

[MWE.zip](https://github.com/BlueBrain/eFEL/files/1252789/MWE.zip)

**Comment by wvangeit** [comment]
With 'sag time constant', do you mean the time constant of the voltage between the start of the stimulus and the sag max ?
I don't think you want to use the 'decay_time_constant_after_stim' efeature for this, because it's used to calculate the DCT 'after' the stimulus, not during.
I saw that you're setting 'decay_end_after_stim' and 'decay_start_after_stim' to values inside the stimulus interval, that's why the 'decay_time_constant_after_stim' fails.
Do we need to implementation an efeature that calculates the DCT between stim_start and the max of the sag ?

**Comment by wvangeit** [comment]
Hi, can I close this ticket ?
