### ISSUE TITLE
check_AISInitiation documentation

### ISSUE THREAD

**Issue by anirban6908** [BlueBrain/eFEL#137]
Hi,
Could you add the documentation for efeature check_AISInitiation? From the code it looks like it returns None when there is no spike in soma, AIS or when the spike initiates in soma before AIS. What is the output when the check passes -  the spikecount?

Thanks

**Comment by wvangeit** [comment]
This was fixed by https://github.com/BlueBrain/eFEL/pull/139

You're correct, None will returned. Which means e.g. in BluePyOpt the feature will get a score of 250.0 stds.
If the test succeeds '1.0' is returned.

The doc is in this section:
http://efel.readthedocs.io/en/latest/eFeatures.html#spike-event-features
