### ISSUE TITLE
Error with stim_start or stim_end

### ISSUE THREAD

**Issue by bioesteel** [BlueBrain/eFEL#197]
Hello, 

This may be a basic error on my part as I am new to python, but I have defined stim_start and stim_end but they are not being recognized. 

A little bit about my dataset -- I extracted data from an .nwb file, where it had been stored in volts and seconds. Must the units be in mV and ms? I also had to calculate the time array from the parameters stored in the .nwb file because the timestamps attribute was empty and only the start time and sampling rate was stored by my acquisition system. I defined stim_start and stim_end as the third and third to last values in the time array because I wanted all of the spikes to be included in the results. 

This is the code I used and the resulting error:
n = nwbfile.acquisition['continuous_signals']
v = n.data[:, 6]
timesamples = np.linspace(0.0, stop = len(v)*(1/30000), num = len(v))
trace1 = {}
trace1['T'] = timesamples
trace1['V'] = v
trace1['stim_start'] = [6.66667520e-05] 
trace1['stim_end'] = [2.60564667e+01]
traces_results = efel.getFeatureValues(trace1, ['AP_amplitude', 'AHP_depth_abs', 'AP_duration_half_widwth', 'AP_width'])

Exception Traceback (most recent call last)
<ipython-input-39-2c17e88b9a6c> in <module>
----> 1 traces_results = efel.getFeatureValues(trace1, ['AP_amplitude', 'AHP_depth_abs', 'AP_duration_half_widwth', 'AP_width'])
~\anaconda3\lib\site-packages\efel\api.py in getFeatureValues(traces, featureNames, parallel_map, return_list, raise_warnings)
    430 
    431     if return_list:
--> 432         return list(map_result)
    433     else:
    434         return map_result

~\anaconda3\lib\site-packages\efel\api.py in _get_feature_values_serial(trace_featurenames)
    468 
    469     else:
--> 470         raise Exception('stim_start or stim_end missing from trace')
    471 
    472     _initialise()

Exception: stim_start or stim_end missing from trace

**Comment by elisabettai** [comment]
Hello,
it may be because the first argument to efel.getFeatureValues should be a list. Does this work for your case?

`traces_results = efel.getFeatureValues([trace1], ['AP_amplitude', 'AHP_depth_abs', 'AP_duration_half_widwth', 'AP_width'])`

I'm guessing based on this example: https://github.com/BlueBrain/eFEL/blob/master/examples/basic/basic_example1.py#L43

**Comment by bioesteel** [comment]
That worked! However, now I am getting a new error. 

"RuntimeWarning: Error while calculating feature AP_width: 
 At least one spike required for calculation of min_AHP_indices.

No spike in trace."

However, this is what my voltage trace looks like:

![image](https://user-images.githubusercontent.com/28160713/105358128-c104ce00-5bc3-11eb-97b7-a53b95eb7ecd.png)

It's actually an electroantennogram (EAG), and not single spikes but I thought maybe I could use this algorithm because the spike shapes in the EAG have similar features to standard spikes. They are voltage peaks from multiple neurons firing at the same time. Must I have my units in ms and mV? They are currently in s and V.

**Comment by wvangeit** [comment]
eFEL was not developed with these kind of EAG traces in mind, but rather for whole-cell current clamp recordings. It assumes the y axis of your trace is in mV in a range that makes sense for these recordings (so around -100 -> 100 mV).
It has e.g. a threshold value used for the spike detection, and it is set by default -20 mV. This value is definitely not appropriate for your trace.
One hack you could try is to scale your trace so that it 'looks' like a whole-cell current clamp recording, but I'm afraid the chance of success is unfortunately very low.

**Comment by bioesteel** [comment]
Thank you for your gracious reply! Makes total sense to have threshold values in the algorithm for detection. I will keep looking for another toolset to employ.
