### ISSUE TITLE
Finding AP threshold 

### ISSUE THREAD

**Issue by shirquinn** [BlueBrain/eFEL#224]
Hi all
Is there a way to correctly detect the AP voltage base for traces of the following type?
I get a low AP threshold because of the EPSP prior to the AP after the stimulation, and I'd like to detect the AP threshold

![stim](https://user-images.githubusercontent.com/67414424/160386248-a43ae290-373e-4f98-b713-25b179b26bba.png)

Thank you

**Comment by wvangeit** [comment]
I would suggest to play a bit with the DerivativeThreshold. It seems the AP start is not sharp enough for the current derivate threshold eFEL uses, an example on how to do that is here:
https://github.com/BlueBrain/eFEL/blob/master/efel/tests/test_basic.py#L461

Otherwise, if you could share a raw trace and the code that you're using for the plot above, @AurelienJaquier could have a look at a different solution.

**Comment by shirquinn** [comment]
Thank you for the quick reply!

when I play with efel.setDoubleSetting('DerivativeThreshold', 22), it works well for some of the traces but not all
for example:

![stim2](https://user-images.githubusercontent.com/67414424/160392495-b5b56f6c-cb02-4612-9e5e-d6fc485767d9.png)

here is the file for example:
[https://drive.google.com/file/d/1uQ8JBYe790ebHFuYLfifI-I08zxoE9N8/view?usp=sharing](url)

its abf, so I upload it like so:

`       abf = pyabf.ABF(file path)
        SweepCount = abf.sweepCount
        Time = abf.sweepX*1000

        for i in range (0,SweepCount): 
            stim_start = 27 
            stim_end = 1000
            abf.setSweep(i)
            trace = {}
            trace['T'] = Time
            trace['V'] = abf.sweepY
            trace['stim_start'] = [stim_start]
            trace['stim_end'] = [stim_end]

            if i == 0:
                traces = [trace]
            else:
                traces.append(trace)`

I'd really appreciate the help
Thank you

**Comment by wvangeit** [comment]
So you mean the blue trace is still not detecting correctly right? Doesn't it work with an even different value for the threshold? 
DerivativeWindow might also help, it's the number of data points during which the derivative threshold has to be crossed:
https://github.com/BlueBrain/eFEL/blob/36b7214e3a138e824c4bcbc80452037203f419f7/efel/tests/test_basic.py#L1285

**Comment by AurelienJaquier** [comment]
Hi there @shirquinn 
I simply changed the derivative threshold to 30 (`efel.setDoubleSetting('DerivativeThreshold', 30)`), and I got the following results:
![test_Issue_224](https://user-images.githubusercontent.com/72930209/160410198-f6714785-3277-41e6-be96-e667775dd57f.png)

Would that be an acceptable solution for you?

**Comment by shirquinn** [comment]
Hi
Thank you very much :)

for traces with a steep slope DerivativeThreshold=30 gives a value that is too high so I'm not sure
and with a high DerivativeWindow it stops finding some of the peaks
more thoughts?

![21705013_sweep_2](https://user-images.githubusercontent.com/67414424/160419213-bd89f541-9476-40db-87bc-7a799faf6961.png)

**Comment by AurelienJaquier** [comment]
It's hard to say on your previous plot, but this threshold detection problem might come from efel's interpolation. EFel interpolates by default the data every 0.1 timewise. In the case you shared, you had much more precise data. The too high value efel returns for some of the traces might be due to this. If you share the data of the plot from your previous comment, I could check if this is indeed the cause of the problem.

Alternatively, I have found that a derivative threshold of 35, and an interpolation step of 0.01 gives good results with the data you already shared. You could check these values on your side with the following lines of code:

```
efel.setDoubleSetting('DerivativeThreshold', 35)
efel.setDoubleSetting('interp_step', 0.01)
```

**Comment by shirquinn** [comment]
OK
so setting the parameters to these solved the problem:
```
    efel.setDoubleSetting('DerivativeThreshold', 30)
    efel.setDoubleSetting('DownDerivativeThreshold',0)
    efel.setIntSetting("DerivativeWindow", 10)
    efel.setDoubleSetting('interp_step', 0.003)
```
Thank you!!!

**Comment by wvangeit** [comment]
👍🏻
