### ISSUE TITLE
Issue in depol_block feature

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/eFEL#278]
@AurelienJaquier  Depol_block returns 1 from last return of the function on this trace, which is not depol block:
[trace.csv](https://github.com/BlueBrain/eFEL/files/11060716/trace.csv)

**Comment by AurelienJaquier** [comment]
Visualisation of the trace: 
![Issue278](https://user-images.githubusercontent.com/72930209/231112756-f6da98e7-0896-4d70-83a5-555ce0735fc7.png)

Basically this happens because of the voltage change at stimulus start going rapidly down and up. AP_begin_voltage is taken when voltage derivative is higher than 10V/s for at least 5 points, which is the case here at stim start. So AP_begin_voltage is bad and it spoils depol_block.
One way of solving this could be to increase the interpolation or the DerivativeWindow.

**Comment by AurelienJaquier** [comment]
If this doesn't work, maybe we would have to use reverse iterators in cpp code to check from the spike and going backward to get the 'last' peak onset, and avoid the shenanigans that happen at stim start.

**Comment by darshanmandge** [comment]
@AurelienJaquier is it a good idea skip a few points to calculate the derivative for depol_block so that we ignore this artefact caused at the onset of stimulus. We can get an idea of points ( or time 0.5-1ms) depending on the average value from other such experimental recordings?

**Comment by AurelienJaquier** [comment]
It is a solution. But I am afraid this might also introduce undesired behavior for some traces. I have made an implementation with backward search from the peak. I think it would be more resilient to false positives as in this issue.

**Comment by AurelienJaquier** [comment]
I'll mark this as solved by PR #287
